# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Path laravel installation
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
# Path GPG & configure
export GPG_TTY=$(tty)
# zsh themes use powerlevel10k
ZSH_THEME="powerlevel10k/powerlevel10k"
## Path NVM_DIR,loads nvm, node, npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 13
# plugins oh-my-zsh
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fast-syntax-highlighting
  zsh-autocomplete
)
# loads oh-my-zsh
source $ZSH/oh-my-zsh.sh
# aliases
alias a="php artisan"
alias g="lazygit"
alias n="npm"
alias c="composer"
alias L="laravel"
alias cd="z"
alias t="tmux"
alias v="nvim"
# ---- Eza (better ls) -----
alias ls="eza --icons=always"
# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# history setup integration white tmux
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify
